spring:
  application:
    name: joboffers
  data:
    mongodb:
      uri: mongodb://root:example@localhost:27017/job-offers?authSource=admin
      auto-index-creation: true

joboffers:
  jobfetcher:
    http:
      client:
        config:
          uri: https://fake-java-offers-api.onrender.com
          connectionTimeOut: 5000
          readTimeOut: 5000
    scheduler:
      joboffers:
        delay: PT3H
scheduling:
  enabled: true